name: ♿ Accessibility Issue
description: Report accessibility barriers or improvements
title: "[A11y]: "
labels: ["accessibility", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping make our platform more accessible! Accessibility is a core value of our project, and we appreciate your feedback.

  - type: dropdown
    id: barrier-type
    attributes:
      label: Accessibility Barrier Type
      description: What type of accessibility issue are you reporting?
      options:
        - Visual/Screen Reader
        - Keyboard Navigation
        - Color/Contrast
        - Motor/Mobility
        - Cognitive/Learning
        - Audio/Hearing
        - Focus Management
        - Form Accessibility
        - Content Structure
        - Alternative Text
        - Video/Media Accessibility
        - Mobile Accessibility
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: wcag-level
    attributes:
      label: WCAG Guideline Level
      description: What WCAG 2.1 level does this relate to? (if known)
      options:
        - Level A
        - Level AA
        - Level AAA
        - Not sure
        - Not applicable

  - type: input
    id: location
    attributes:
      label: Page/Component Location
      description: Where did you encounter this accessibility issue?
      placeholder: e.g., Login page, Course editor, Assessment interface, Navigation menu
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the accessibility barrier you encountered
      placeholder: |
        Clearly describe:
        - What accessibility barrier you encountered
        - What you were trying to accomplish
        - How this barrier prevented you from completing your task
    validations:
      required: true

  - type: textarea
    id: assistive-technology
    attributes:
      label: Assistive Technology Used
      description: What assistive technology or tools were you using?
      placeholder: |
        Please specify:
        - Screen reader (NVDA, JAWS, VoiceOver, etc.) and version
        - Browser and version
        - Operating system
        - Keyboard navigation only
        - Voice control software
        - Other assistive technology

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Accessible Behavior
      description: What should happen for this to be accessible?
      placeholder: |
        Describe what you expected:
        - How should this work with assistive technology?
        - What accessible alternatives should be available?
        - What ARIA labels or roles should be present?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Describe what actually occurred:
        - Error messages or lack of feedback
        - Missing or incorrect announcements
        - Navigation issues
        - Content that couldn't be accessed
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severely does this impact accessibility?
      options:
        - Critical (Completely blocks access to essential functionality)
        - High (Significantly impairs ability to use the feature)
        - Medium (Creates difficulty but workarounds exist)
        - Low (Minor accessibility improvement)
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce this accessibility issue
      placeholder: |
        1. Navigate to [page/component]
        2. Using [assistive technology], attempt to [action]
        3. Observe [accessibility barrier]
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: Do you have suggestions for how to fix this accessibility issue?
      placeholder: |
        Potential solutions:
        - ARIA attributes to add
        - HTML structure changes
        - Keyboard interaction patterns
        - Alternative content formats
        - Focus management improvements

  - type: checkboxes
    id: wcag-criteria
    attributes:
      label: WCAG 2.1 Success Criteria
      description: Which WCAG success criteria does this relate to? (check all that apply)
      options:
        - label: "1.1.1 Non-text Content (Images need alt text)"
        - label: "1.3.1 Info and Relationships (Proper heading structure)"
        - label: "1.4.3 Contrast (Minimum color contrast)"
        - label: "1.4.11 Non-text Contrast (UI component contrast)"
        - label: "2.1.1 Keyboard (Keyboard accessibility)"
        - label: "2.1.2 No Keyboard Trap (Focus management)"
        - label: "2.4.1 Bypass Blocks (Skip links)"
        - label: "2.4.3 Focus Order (Logical focus sequence)"
        - label: "2.4.6 Headings and Labels (Descriptive headings)"
        - label: "2.4.7 Focus Visible (Visible focus indicators)"
        - label: "3.1.1 Language of Page (Page language specified)"
        - label: "3.2.1 On Focus (No unexpected context changes)"
        - label: "3.3.1 Error Identification (Clear error messages)"
        - label: "3.3.2 Labels or Instructions (Form labels)"
        - label: "4.1.1 Parsing (Valid HTML)"
        - label: "4.1.2 Name, Role, Value (Proper ARIA)"
        - label: "4.1.3 Status Messages (Live regions)"

  - type: textarea
    id: testing-tools
    attributes:
      label: Accessibility Testing Tools Used
      description: What tools did you use to identify this issue?
      placeholder: |
        Testing tools used:
        - Manual testing with [assistive technology]
        - Automated tools (axe, WAVE, Lighthouse, etc.)
        - Browser developer tools
        - Color contrast analyzers
        - Keyboard navigation testing

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: How does this accessibility barrier affect users?
      placeholder: |
        Impact on users:
        - Which user groups are affected?
        - What tasks become impossible or difficult?
        - How does this affect the learning experience?
        - Are there any workarounds available?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in helping fix this accessibility issue?
      options:
        - label: I can help implement the fix
        - label: I can help with accessibility testing
        - label: I can provide ongoing feedback during development
        - label: I can help with accessibility documentation
        - label: I can help test with specific assistive technology

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help address this accessibility issue
      placeholder: |
        Additional information:
        - Screenshots or screen recordings
        - Links to accessibility guidelines
        - Examples from other accessible applications
        - Specific user scenarios affected

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this accessibility issue hasn't been reported before
          required: true
        - label: I have provided specific details about the assistive technology used
          required: true
        - label: I understand that accessibility improvements benefit all users
          required: true