blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussion
    url: https://github.com/personalized-lms/personalized-lms/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🔒 Security Vulnerability
    url: mailto:security@personalized-lms.org
    about: Report security vulnerabilities privately (do not create public issues)
  - name: 📖 Documentation
    url: https://docs.personalized-lms.org
    about: Check our comprehensive documentation and guides
  - name: 💬 Discord Community
    url: https://discord.gg/personalized-lms
    about: Join our Discord server for real-time community support